# Generated by Django 4.2.4 on 2023-12-01 09:33

from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Categoriya nomi')),
            ],
            options={
                'verbose_name': 'Kategoriya',
            },
        ),
        migrations.CreateModel(
            name='FileBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='audio/', validators=[news.models.validate_file], verbose_name='Faylni tanlang')),
            ],
            options={
                'verbose_name': 'Malumot fayl',
            },
        ),
        migrations.CreateModel(
            name='ImageNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='yes/', verbose_name='rasm yuklash')),
            ],
            options={
                'verbose_name': "Rasm qo'shish",
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videos', models.FileField(blank=True, null=True, upload_to='video/', verbose_name='Videolar')),
            ],
            options={
                'verbose_name': 'Videolar',
            },
        ),
        migrations.CreateModel(
            name='Videogallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(verbose_name='rasmlar haqida')),
                ('categ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
                ('video', models.ManyToManyField(related_name='video', to='news.video')),
            ],
            options={
                'verbose_name': 'VideoGaleriya',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300, verbose_name='Yangilik nomi')),
                ('title', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='news.category')),
                ('images', models.ManyToManyField(related_name='images', to='news.imagenews')),
            ],
            options={
                'verbose_name': 'Yangilik',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300, verbose_name='Malumot nomi')),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
                ('file', models.ManyToManyField(related_name='file', to='news.filebook')),
            ],
            options={
                'verbose_name': 'Malumotlar',
            },
        ),
        migrations.CreateModel(
            name='Fotogallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(verbose_name='rasmlar haqida')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
                ('img', models.ManyToManyField(related_name='img', to='news.imagenews')),
            ],
            options={
                'verbose_name': 'FotoGaleriya',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Rasm nomi')),
                ('img', models.ImageField(upload_to='img/', verbose_name='Tadbir rasmlari')),
                ('body', models.TextField(verbose_name='rasmlar haqida')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
            ],
            options={
                'verbose_name': 'Tadbirlar',
            },
        ),
    ]
