# Generated by Django 4.2.4 on 2023-12-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200, verbose_name='Foylanuvchi ismi')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=100, verbose_name='Telefon raqami')),
                ('subject', models.CharField(max_length=300, verbose_name='Mavzu nomi')),
                ('message', models.CharField(max_length=200, verbose_name='Xabar matni')),
            ],
            options={
                'verbose_name': 'Xabarlar',
            },
        ),
    ]
