# Generated by Django 4.2.4 on 2023-12-01 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Foydalanuvchi_'},
        ),
    ]
