# Generated by Django 4.2.4 on 2023-12-01 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Kategoriya nomi')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tizim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=299, verbose_name='Tuzilma nomi')),
                ('image', models.ImageField(upload_to='tizim/', verbose_name='')),
                ('body', models.CharField(max_length=299, verbose_name='Tuzilma haqida')),
            ],
            options={
                'verbose_name': 'Agentlik tuzilmasi',
            },
        ),
        migrations.CreateModel(
            name='RegionOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=300, verbose_name="Boshliq to'liq ismi ")),
                ('image', models.ImageField(upload_to='img/')),
                ('position', models.CharField(max_length=200, verbose_name='Rahbar lavozimi')),
                ('facebook', models.CharField(max_length=100, verbose_name='Facebook lichkasi')),
                ('whatsapp', models.CharField(max_length=100, verbose_name='Whatsapp lichkasi')),
                ('instagram', models.CharField(max_length=100, verbose_name='Instagram lichkasi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leader.category')),
            ],
            options={
                'verbose_name': 'Hudud boshqarmasi',
            },
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300, verbose_name='Maqsad va vazifa nomi')),
                ('title', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leader.category')),
            ],
            options={
                'verbose_name': 'Maqsad va vazifa',
            },
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=300, verbose_name='Rahbarni toliq ismi ')),
                ('position', models.CharField(max_length=200, verbose_name='Rahbar lavozimi')),
                ('image', models.ImageField(upload_to='image/')),
                ('phone', models.CharField(max_length=40, verbose_name='telefon nomeri')),
                ('email', models.EmailField(max_length=254, verbose_name='Elektron pochtasi')),
                ('facebook', models.CharField(max_length=100, verbose_name='Facebook lichkasi')),
                ('whatsapp', models.CharField(max_length=100, verbose_name='Whatsapp lichkasi')),
                ('instagram', models.CharField(max_length=100, verbose_name='Instagram lichkasi')),
                ('admission_days', models.CharField(max_length=400, verbose_name='Qabul qilish kunlari')),
                ('work_activity', models.CharField(max_length=200, verbose_name='Ish faoliyati')),
                ('tasks_functions', models.CharField(max_length=300, verbose_name='Vazifa va funsiyalari')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leader.category')),
            ],
            options={
                'verbose_name': 'Rahbar',
            },
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='about/')),
                ('title', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leader.category')),
            ],
            options={
                'verbose_name': 'Biz haqimzda',
            },
        ),
    ]
