# Generated by Django 4.2.4 on 2023-10-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectname',
            name='name',
            field=models.CharField(default=2, max_length=200, verbose_name='Loyiha nomi'),
            preserve_default=False,
        ),
    ]
